name: Test

#run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest # где запускаем
    steps: # что делаем
      - uses: actions/checkout@v3 # выкачиваем репозиторий
      - uses: actions/setup-java@v3 # настраиваем java
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub # запуск тестов

      # скачиваем историю тестов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # генерируем отчёт
      - uses: simple-elf/allure-report-action@main
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      # публикуем отчёт
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

#      - name: Post the link to the report
#        if: always()
#        uses: Sibz/github-status-action@v1
#        with:
#          authToken: ${{secrets.GITHUB_TOKEN}}
#          context: 'Test report'
#          state: 'success'
#          sha: ${{ github.event.pull_request.head.sha }}
#          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}